kind: Service
apiVersion: v1
metadata:
  name: outside-3
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "3"
  ports:
  - protocol: TCP
    targetPort: 5556
    port: 32401
    nodePort: 30003
  type: NodePort
