kind: Service
apiVersion: v1
metadata:
  name: outside-3
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "3"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32403
    nodePort: 32403
  type: NodePort
