kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 5556
    port: 32401
    nodePort: 30002
  type: NodePort
