kind: Service
apiVersion: v1
metadata:
  name: outside-5
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "5"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32405
    nodePort: 32405
  type: NodePort
