kind: Service
apiVersion: v1
metadata:
  name: outside-4
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "4"
  ports:
  - protocol: TCP
    targetPort: 5556
    port: 32401
    nodePort: 30004
  type: NodePort
