kind: Service
apiVersion: v1
metadata:
  name: outside-5
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "5"
  ports:
  - protocol: TCP
    targetPort: 5556
    port: 32401
    nodePort: 30005
  type: NodePort
