kind: Service
apiVersion: v1
metadata:
  name: outside-4
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "4"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32404
    nodePort: 32404
  type: NodePort
