# the headless service is for PetSet DNS, this one is for clients
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 31111
  selector:
    app: zookeeper
