apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels: 
    app: kafka-exporter 
spec:
  selector:
    app: kafka-exporter
  ports:
  - name: http-metrics
    port: 9308
    protocol: TCP
    targetPort: 9308
    nodePort: 30055
  type: NodePort
