---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  ports:
    - name: prometheus-node-exporter
      port: 9100
      nodePort: 30088
      protocol: TCP
  selector:
    app: prometheus
    component: node-exporter
  type: NodePort
