---
apiVersion: batch/v1
kind: Job
metadata:
  name: topic-test-produce-consume
  namespace: test-kafka
spec:
  template:
    spec:
      containers:
      - name: topic-create
        image: solsson/kafka:native-cli@sha256:fbf29c59182fb87921c5199783d2d5796856ecbfe34a9c03eca658b3cf50f3c4
        command:
        - ./bin/kafka-topics.sh
        - --bootstrap-server
        -   bootstrap.kafka.svc.cluster.local:9092
        - --create
        - --topic
        -   test-produce-consume
        resources:
          limits:
            cpu: 100m
            memory: 20Mi
      restartPolicy: Never
